### ISSUE TITLE
Add libp2p resource manager

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/rainbow#10]
We might check what customization over the default the current gateways are using and let that be configurable too.

**Comment by BigLep** [comment]
Two thoughts on this:
1. I think we should take a similar approach to Kubo for configuring the resource manager: https://github.com/ipfs/kubo/blob/master/docs/libp2p-resource-management.md
2. Lets expose the resource manager metrics: https://github.com/ipfs/kubo/pull/9947
