### ISSUE TITLE
Debug endpoint to check peering status

### ISSUE THREAD

**Issue by hacdias** [ipfs/rainbow#130]
It would be advantageous if we have a debug endpoint where we can check the peering status. This can be especially useful if we're using seed-based automatic peering.

The only way of checking it now is using `GOLOG_LOG_LEVEL="peering=debug"` and checking the debug logs.

**Comment by gammazero** [comment]
In #194 a new management endpoint was added that shows the current peers:
- http://$RAINBOW_CTL_LISTEN_ADDRESS/mgr/peers returns a list of currently connected peers

I am not sure if this is exactly what you are looking for, but if it is please close this issue.

**Comment by hacdias** [comment]
I think this issue was created when we introduced peering in Rainbow. The idea was to have an endpoint where we could properly monitor whether the instances were getting automatically connected to their peers (https://github.com/ipfs/rainbow/pull/111).

**Comment by gammazero** [comment]
I think this is handled in #194, unless there is a further request. If endpoint needs to be exposed outside of localhost, then is up to operator.
