### ISSUE TITLE
Bootstrapping and peering

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/rainbow#27]
We need a way to boostrap and peer to a set of fixed nodes.

Pending:

* https://github.com/ipfs/boxo/pull/474
* https://github.com/ipfs/boxo/pull/473

**Comment by 2color** [comment]
@lidel Seems that this would be relevant for us to solve some of the problems with retrievability across the gateway Rainbow nodes. Specifically, when one gateway node has a given block while another which handles a request does not.
