### ISSUE TITLE
Performance benchmarking

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/rainbow#31]
I tested Kubo 0.23.0 vs Rainbow (master) on Thunderdome.

We see rainbow is like 5x faster in ttfb metrics:

![image](https://github.com/ipfs/rainbow/assets/1027022/449a50aa-f812-4be0-b414-80f0dce1e57c)

Rainbow uses many less resources than Kubo. I.e. 10x less mean heap usage. 5x less goroutines. 6x less CPU.

![image](https://github.com/ipfs/rainbow/assets/1027022/d1c1714c-5e24-4b75-9545-6e637bf63dc2)

Rainbow has similar request metrics, seems to be slightly faster.

![image](https://github.com/ipfs/rainbow/assets/1027022/cc352182-7ac6-4c12-91d3-ab9c25881ab7)

Looking in the time dimension, Kubo has waves where TTFB increases greatly, where rainbow doesn't:

![image](https://github.com/ipfs/rainbow/assets/1027022/17753b0a-d024-458f-955e-35fc63544f43)

In general Rainbow appears to be much more performance in terms of resource usage than Kubo, for slightly better results when processing requests in terms of return codes (with the exception of TTFB, where rainbow is much better), although we see similar graphs of dropped requests/timeouts:

![image](https://github.com/ipfs/rainbow/assets/1027022/24fb4188-6c84-49d5-8e0b-60dfd823abea)

**Comment by BigLep** [comment]
@ns4plabs (or others): are there other steps here?

**Comment by hacdias** [comment]
As per the triage meeting, I'm closing this issue. There's no actionable items in this issue, and there are already Grafana dashboard where we can currently monitor Kubo and Rainbow.

Thunderdome improvements will be tackled separately.
