### ISSUE TITLE
End-to-end configuration tests

### ISSUE THREAD

**Issue by lidel** [ipfs/rainbow#89]
Rainbow needs end-to-end regression tests that  build binary and confirm sensitive configuration is applied correctly:
- [ ] confirm env `RAINBOW_TRUSTLESS_GATEWAY_DOMAINS` is applied correctly
- [ ] confirm cli param `--trustless-gateway-domains` is applied correctly

We can't afford regression in trustless-only mode, but once we have end-to-end setup, we cna test more with it.

**Comment by hacdias** [comment]
I think the trick here is isolating all tests, or not running any E2E tests in parallel.
